name: TK-TODO Check # IGNORE:TK

on:
  push:
    branches:
      - master
  pull_request: {}

permissions:
  contents: read

jobs:
  tk-todo-check: # IGNORE:TK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check for TK-TODO markers # IGNORE:TK
        uses: aaronsteers/tk-todo-check-action@v1.0.0 # IGNORE:TK
